### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Ame-chan-angel** [faveoled/yuki-iptv-unofficial-snap#1]
**Steps to reproduce:**
- Boot from Debian Live ISO (**debian-live-12.4.0-amd64-kde.iso**)
- Run commands:

```
sudo apt update
sudo apt install snapd
sudo snap install core
sudo snap install yuki-iptv-unofficial
```

- Log out and login with password **live**
- Launch yuki-iptv from applications list

**Got error:**
```
yuki-iptv error

Traceback (most recent call last):
  File "/snap/yuki-iptv-unofficial/1/usr/lib/yuki-iptv/./yuki-iptv.py", line 489, in <module>
    from thirdparty import mpv
  File "/snap/yuki-iptv-unofficial/1/usr/lib/yuki-iptv/thirdparty/mpv.py", line 54, in <module>
    raise OSError("Cannot find libmpv in the usual places. Depending on your distro, you may try installing an "
OSError: Cannot find libmpv in the usual places. Depending on your distro, you may try installing an mpv-devel or mpv-libs package. If you have libmpv around but this script can't find it, consult the documentation for ctypes.util.find_library which this script uses to look up the library filename.
```

**Comment by faveoled** [comment]
Not sure what that's about. Looks like a snap bug to me. A reboot might help

**Comment by faveoled** [comment]
Ubuntu 20.04.5, installed. Has mov error, fixed using this:
```
sudo apt install libmpv1
```
ImageMackick can be solved similarly I guess.
Not sure why confined snap interacts with the system.

**Comment by faveoled** [comment]
Seems to be related to this:
https://forum.snapcraft.io/t/issue-when-snap-uses-pythons-ctype-util-find-library/9690/1

**Comment by faveoled** [comment]
Should be fixed in the latest build
